# Numpy_Example_list

11-7-23


1.  ...


In [1]:
#1. ...
import numpy as np
a = np.arange(13)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2]:
from numpy import *
a = arange(12)
a = a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [3]:
b = np.arange(15)


In [4]:
a[...,0]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [5]:
a[:,:,0]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [6]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [7]:
a[1:]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [8]:
a[1:,...]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [9]:
from numpy import *
b= arange(15)
b= b.reshape(3,5,1)
b

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [10]:

c= arange(10)
c= c.reshape(2,5,1)
c

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [11]:
c

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [12]:
c[1:]

array([[[5],
        [6],
        [7],
        [8],
        [9]]])

In [13]:
c[1:,...]

array([[[5],
        [6],
        [7],
        [8],
        [9]]])

In [14]:
c[0:,...]

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [15]:
d= arange(19)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [16]:
x = arange(20)
x = x.reshape(2,5,2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [17]:
x = x.reshape(2,10,1)
x

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]]])

In [18]:
x = x.reshape(5,2,2)
x

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [19]:
x[...,0]     #x[:,:,0]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [20]:
x[...,1]    #x[:,:,1]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [21]:
x[1,...]   #x[1,:,:]

array([[4, 5],
       [6, 7]])

In [22]:
x[1:,...]  #x[1:,:,:]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [23]:
x[2:,...]

array([[[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [24]:
x[2,...]

array([[ 8,  9],
       [10, 11]])

In [25]:
x[...,2]

IndexError: index 2 is out of bounds for axis 2 with size 2

In [38]:
ab = arange(30)
ab = ab.reshape(3,2,5)
ab

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [39]:
ab[...,0]

array([[ 0,  5],
       [10, 15],
       [20, 25]])

In [40]:
ab[0,...]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
ab[1,...]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
ab[...,1]

array([[ 1,  6],
       [11, 16],
       [21, 26]])

In [43]:
ab[...,4]

array([[ 4,  9],
       [14, 19],
       [24, 29]])

In [44]:
ab

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [45]:
ab[1:,...]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [46]:
ab[...,:-1]

array([[[ 0,  1,  2,  3],
        [ 5,  6,  7,  8]],

       [[10, 11, 12, 13],
        [15, 16, 17, 18]],

       [[20, 21, 22, 23],
        [25, 26, 27, 28]]])

In [47]:
ab[...,2]

array([[ 2,  7],
       [12, 17],
       [22, 27]])

In [48]:
ab[...,:2]

array([[[ 0,  1],
        [ 5,  6]],

       [[10, 11],
        [15, 16]],

       [[20, 21],
        [25, 26]]])

In [49]:
ab

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

2. []


In [50]:
a = array([[0,1,2,3,4], [10,11,12,13,14], [20,21,22,23,24], [30,31,32,33,34]])
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [51]:
a[0][0]

0

In [52]:
a[0][2]

2

In [53]:
a[2][1]

21

In [54]:
a[-1]

array([30, 31, 32, 33, 34])

In [55]:
print(type(a))

<class 'numpy.ndarray'>


In [56]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [57]:
a[2,3]

23

In [58]:
a[1:3,1:4]

array([[11, 12, 13],
       [21, 22, 23]])


2. []


In [59]:
a = array([[0,1,2,3,4], [10,11,12,13,14], [20,21,22,23,24],[30,31,32,33,34]])

In [60]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [61]:
a[0,0]

0

In [62]:
type(a)

numpy.ndarray

In [63]:
a[1,5]

IndexError: index 5 is out of bounds for axis 1 with size 5

In [64]:
a[1,4]

14

In [65]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [66]:
a[0]

array([0, 1, 2, 3, 4])

In [67]:
a[-1]

array([30, 31, 32, 33, 34])

In [68]:
a[1:3,1:4]  #subarray

array([[11, 12, 13],
       [21, 22, 23]])

In [69]:
a[1:3,2:4]

array([[12, 13],
       [22, 23]])

In [70]:
'''
>>> i = array([0,1,2,1]) # array of indices for the first axis
>>> j = array([1,2,3,4]) # array of indices for the second axis
>>> a[i,j]
array([ 1, 12, 23, 14])
>>>
>>> a[a<13] # boolean indexing
array([ 0, 1, 2, 3, 4, 10, 11, 12])
'''

'\ni = array([0,1,2,1]) # array of indices for the first axis\nj = array([1,2,3,4]) # array of indices for the second axis\na[i,j]\narray([ 1, 12, 23, 14])\n\na[a<13] # boolean indexing\narray([ 0, 1, 2, 3, 4, 10, 11, 12])\n'

In [71]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [72]:
b1=array([True,False,True,False])   #boolean row selector
a[b1,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [73]:
b2 = array([True,False,False,True,True])    #boolean column selector
a[:,b2]

array([[ 0,  3,  4],
       [10, 13, 14],
       [20, 23, 24],
       [30, 33, 34]])

In [74]:
a[a<13]        #boolean indexing

array([ 0,  1,  2,  3,  4, 10, 11, 12])


3. abs()
4. absolute()


In [75]:
abs(-3)

3

In [76]:
abs(array([-1.7,-1.2]))

array([1.7, 1.2])

In [77]:
abs(1+3j)

3.1622776601683795

In [78]:
abs(1.5+2j)

2.5

In [79]:
abs(True)

1

In [80]:
abs(0b10)

2

In [81]:
abs(0o234)

156

In [82]:
abs(~18)

19

In [83]:
abs(23^56)

47

In [84]:
abs(21 & 7)

5


5. accumulate()


In [85]:
add.accumulate(array([1.,2.,3.,4.]))  #Accumulate the result of applying the operator to all elements.

array([ 1.,  3.,  6., 10.])

In [86]:
import numpy as np

In [87]:
np.add.accumulate(array([1,2,3,4]))

array([ 1,  3,  6, 10])

In [88]:
np.multiply.accumulate(array([1,2,3,4]))

array([ 1,  2,  6, 24])

In [89]:
'''
2-D array examples:

>>> I = np.eye(2)
>>> I
array([[1.,  0.],
       [0.,  1.]])

Accumulate along axis 0 (rows), down columns:

>>> np.add.accumulate(I, 0)
array([[1.,  0.],
       [1.,  1.]])
>>> np.add.accumulate(I) # no axis specified = axis zero
array([[1.,  0.],
       [1.,  1.]])

Accumulate along axis 1 (columns), through rows:

>>> np.add.accumulate(I, 1)
array([[1.,  1.],
       [0.,  1.]])
Type:      builtin_function_or_method
'''

'\n2-D array examples:\n\n>>> I = np.eye(2)\n>>> I\narray([[1.,  0.],\n       [0.,  1.]])\n\nAccumulate along axis 0 (rows), down columns:\n\n>>> np.add.accumulate(I, 0)\narray([[1.,  0.],\n       [1.,  1.]])\n>>> np.add.accumulate(I) # no axis specified = axis zero\narray([[1.,  0.],\n       [1.,  1.]])\n\nAccumulate along axis 1 (columns), through rows:\n\n>>> np.add.accumulate(I, 1)\narray([[1.,  1.],\n       [0.,  1.]])\nType:      builtin_function_or_method\n'

In [90]:
'''
Return a 2-D array with ones on the diagonal and zeros elsewhere.
'''
I = eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [91]:
add.accumulate(I,0) #axis =0 (rows) , down columns

array([[1., 0.],
       [1., 1.]])

In [92]:
add.accumulate(I)  #default axis =0

array([[1., 0.],
       [1., 1.]])

In [93]:
add.accumulate(I,1)  #axis =1 (columns)  ,thru rows

array([[1., 1.],
       [0., 1.]])

In [94]:
I = eye(3,3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
add.accumulate(I)  #default axis 0 (rows) i.e down columns

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [96]:
add.accumulate(I,1)

array([[1., 1., 1.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [97]:
multiply.accumulate(array([1.,2.,3.,4.]), dtype = int)

array([ 1,  2,  6, 24])

In [98]:
divide.accumulate(array([1,2,3,4]))

array([1.        , 0.5       , 0.16666667, 0.04166667])

In [99]:
add.accumulate(array([[1,2,3],[4,5,6]]),axis=0)  #accumulate every column seperately

array([[1, 2, 3],
       [5, 7, 9]])

In [100]:
add.accumulate(array([[1,2,3],[4,5,6]]),axis=1)   #accumulate every row seperately

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [101]:
add.accumulate(array([1,2,3,4]))

array([ 1,  3,  6, 10])


6. add()


In [102]:
add(array([1.3,4]), array([-0.3,-5]))

array([ 1., -1.])

In [103]:
array([1.3,4]) + array([-0.3,-5])

array([ 1., -1.])


7. all()


In [104]:
a = array([True,False,True,True])
all(a)
#a.all()

False

In [105]:
a = array([1,2,3])
all(a>0)
#(a>0).all()

True


8. allclose()


In [106]:
'''
Signature: allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
Docstring:
Returns True if two arrays are element-wise equal within a tolerance.

The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

a and b: These are the input arrays to be compared.
rtol (optional): The relative tolerance parameter. The default value is 1e-05.
atol (optional): The absolute tolerance parameter. The default value is 1e-08.
equal_nan (optional): If True, then NaN values are considered equal. The default value is False.
'''

'\nSignature: allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)\nDocstring:\nReturns True if two arrays are element-wise equal within a tolerance.\n\nThe tolerance values are positive, typically very small numbers.  The\nrelative difference (`rtol` * abs(`b`)) and the absolute difference\n`atol` are added together to compare against the absolute difference\nbetween `a` and `b`.\n\na and b: These are the input arrays to be compared.\nrtol (optional): The relative tolerance parameter. The default value is 1e-05.\natol (optional): The absolute tolerance parameter. The default value is 1e-08.\nequal_nan (optional): If True, then NaN values are considered equal. The default value is False.\n'

In [107]:
allclose(array([1e10,1e-8]), array([1.00001e10, 1e-9]))

True

In [108]:
allclose(array([1,2,3]),array([2,4,6]))

False


9. alltrue()


In [109]:
a = array([True,True,True])
alltrue(a)

True

In [110]:
a= array([4,5,6,7,8])
alltrue(a>=4)

True

In [111]:
a= array([1,2,3,4,5,6,7,8])
alltrue(a>=4)

False


10. angle()


In [112]:
'''
Signature: angle(z, deg=False)
Docstring:
Return the angle of the complex argument.

Parameters
----------
z : array_like
    A complex number or sequence of complex numbers.
deg : bool, optional
    Return angle in degrees if True, radians if False (default).
'''

'\nSignature: angle(z, deg=False)\nDocstring:\nReturn the angle of the complex argument.\n\nParameters\n----------\nz : array_like\n    A complex number or sequence of complex numbers.\ndeg : bool, optional\n    Return angle in degrees if True, radians if False (default).\n'

In [113]:
'''
Examples
--------
>>> np.angle([1.0, 1.0j, 1+1j])               # in radians
array([ 0.        ,  1.57079633,  0.78539816]) # may vary
>>> np.angle(1+1j, deg=True)                  # in degrees
45.0
'''

'\nExamples\n--------\n>>> np.angle([1.0, 1.0j, 1+1j])               # in radians\narray([ 0.        ,  1.57079633,  0.78539816]) # may vary\n>>> np.angle(1+1j, deg=True)                  # in degrees\n45.0\n'

In [114]:
angle(1+5j)    #deg = False ,gives in radians

1.373400766945016

In [115]:
print(type(angle(1+5j)))

<class 'numpy.float64'>


In [116]:
angle(1+5j, deg = True)  #deg = True ,gives in degrees

78.69006752597979

In [117]:
angle([1.0, 1.0j, 1+1j])

array([0.        , 1.57079633, 0.78539816])

In [118]:
angle(1+1j, deg= True)

45.0